export const MOCK_GAMES = [
  {
    slug: "super-mario-wonder",
    title: "Super Mario Bros Wonder",
    description: "Una nueva aventura de Mario en 2D con efectos sorprendentes.",
    descriptionTwo: "Super Mario Bros. Wonder es un juego de plataformas en 2D desarrollado por Nintendo para la consola Nintendo Switch. Lanzado el 20 de octubre de 2023, el juego presenta a Mario y sus amigos embarcándose en una nueva aventura a través del Reino Champiñón, que ha sido transformado por unas misteriosas flores llamadas Wonder Flowers. Estas flores otorgan habilidades únicas a los personajes y alteran el entorno de maneras sorprendentes, ofreciendo nuevas mecánicas de juego y desafíos para los jugadores.",
    releaseDate: "2023-10-20",
    score: 92,
    image: "https://sm.ign.com/ign_latam/cover/s/super-mari/super-mario-bros-wonder_33js.jpg",
  },
  {
    slug: "elden-ring",
    title: "Elden Ring",
    description: "Un juego de acción y rol de mundo abierto ambientado en las Tierras Intermedias.",
    descriptionTwo: "Elden Ring es un videojuego de acción y rol desarrollado por FromSoftware y publicado por Bandai Namco Entertainment. Lanzado en febrero de 2022, el juego fue dirigido por Hidetaka Miyazaki, conocido por su trabajo en la serie Dark Souls, y contó con la colaboración del autor George R. R. Martin, quien ayudó a crear el trasfondo del mundo del juego. Elden Ring se destaca por su vasto mundo abierto, su desafiante jugabilidad y su profunda narrativa, ofreciendo a los jugadores una experiencia inmersiva en un entorno lleno de misterios y peligros.",
    releaseDate: "2022-02-25",
    score: 96,
    image: "https://assets.xboxservices.com/assets/7b/54/7b54f5e4-0857-4ce3-8a18-2b8c431e8a9e.jpg?n=Elden-Ring_GLP-Page-Hero-0_1083x1222_01.jpg",
  },
  {
    slug: "the-legend-of-zelda-tears-of-the-kingdom",
    title: "Zelda: Tears of the Kingdom",
    description: "La épica secuela de Breath of the Wild con nuevas mecánicas de construcción.",
    descriptionTwo: "The Legend of Zelda: Tears of the Kingdom es un videojuego de acción y rol desarrollado por Nintendo para la consola Nintendo Switch. Lanzado el 12 de mayo de 2023, el juego es la secuela directa de Breath of the Wild y presenta a Link explorando un mundo lleno de misterios, con nuevas mecánicas que permiten construir estructuras y manipular el entorno para resolver acertijos.",
    releaseDate: "2023-05-12",
    score: 96,
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg/250px-The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg",
  },
  {
    slug: "god-of-war-ragnarok",
    title: "God of War: Ragnarok",
    description: "Kratos y Atreus enfrentan el fin del mundo en la mitología nórdica.",
    descriptionTwo: "God of War: Ragnarok es un videojuego de acción y aventura desarrollado por Santa Monica Studio y publicado por Sony Interactive Entertainment. Lanzado en noviembre de 2022 para PlayStation 4 y PlayStation 5, el juego continúa la historia de Kratos y su hijo Atreus mientras enfrentan el inminente fin del mundo, conocido como Ragnarok, en un entorno inspirado en la mitología nórdica.",
    releaseDate: "2022-11-09",
    score: 94,
    image: "https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnarök_cover.jpg",
  },
  {
    slug: "horizon-forbidden-west",
    title: "Horizon Forbidden West",
    description: "Explora un mundo post-apocalíptico lleno de criaturas mecánicas.",
    descriptionTwo: "Horizon Forbidden West es un videojuego de acción y rol desarrollado por Guerrilla Games y publicado por Sony Interactive Entertainment. Lanzado en febrero de 2022 para PlayStation 4 y PlayStation 5, el juego es la secuela de Horizon Zero Dawn y sigue a la protagonista Aloy mientras explora el oeste prohibido, una región llena de peligrosas criaturas mecánicas y misterios por descubrir.",
    releaseDate: "2022-02-18",
    score: 88,
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/6/69/Horizon_Forbidden_West_cover_art.jpg/250px-Horizon_Forbidden_West_cover_art.jpg",
  },
  {
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    description: "Un RPG de mundo abierto en una metrópolis futurista.",
    descriptionTwo: "Cyberpunk 2077 es un videojuego de rol y acción desarrollado por CD Projekt Red. Lanzado en diciembre de 2020, el juego está ambientado en la distópica metrópolis de Night City, donde los jugadores asumen el papel de V, un mercenario que busca un implante único que otorga la inmortalidad. A pesar de su lanzamiento problemático, el juego ha recibido numerosas actualizaciones y expansiones que han mejorado significativamente la experiencia del jugador.",
    releaseDate: "2020-12-10",
    score: 85,
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Cyberpunk_2077_box_art.jpg/250px-Cyberpunk_2077_box_art.jpg",
  },
  {
    slug: "resident-evil-village",
    title: "Resident Evil Village",
    description: "La octava entrega principal de la serie Resident Evil.",
    descriptionTwo: "Resident Evil Village es un videojuego de terror y supervivencia desarrollado y publicado por Capcom. Lanzado en mayo de 2021, el juego es la octava entrega principal de la serie Resident Evil y continúa la historia de Ethan Winters, quien se encuentra en un misterioso pueblo europeo lleno de criaturas aterradoras y secretos oscuros.",
    releaseDate: "2021-05-07",
    score: 84,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202101/0812/FkzwjnJknkrFlozkTdeQBMub.png",
  },
  {
    slug: "call-of-duty-modern-warfare-2-2022",
    title: "Call of Duty: Modern Warfare 2 (2022)",
    description: "La última entrega de la serie Modern Warfare con acción intensa.",
    descriptionTwo: "Call of Duty: Modern Warfare 2 es un videojuego de disparos en primera persona desarrollado por Infinity Ward y publicado por Activision. Lanzado en octubre de 2022, el juego es una secuela directa del reinicio de Modern Warfare de 2019 y ofrece una campaña intensa, así como modos multijugador y cooperativos que continúan la tradición de la serie.",
    releaseDate: "2022-10-28",
    score: 83,
    image: "https://image.api.playstation.com/vulcan/img/rnd/202008/1301/raryqz0xAsk3HutslehRAW4A.png",
  },
  {
    slug: "forza-horizon-5",
    title: "Forza Horizon 5",
    description: "Un juego de carreras ambientado en un mundo abierto basado en México.",
    descriptionTwo: "Forza Horizon 5 es un videojuego de carreras desarrollado por Playground Games y publicado por Xbox Game Studios. Lanzado en noviembre de 2021, el juego está ambientado en un mundo abierto basado en México, ofreciendo a los jugadores una amplia variedad de vehículos y eventos para explorar en un entorno vibrante y detallado.",
    releaseDate: "2021-11-09",
    score: 92,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202501/2717/42b3ee6b1b2094212231b0b0a82824f687fc5c4dc9bde31c.png",
  },
  {
    slug: "animal-crossing-new-horizons",
    title: "Animal Crossing: New Horizons",
    description: "Un simulador de vida en una isla desierta.",
    descriptionTwo: "Animal Crossing: New Horizons es un videojuego de simulación de vida desarrollado y publicado por Nintendo para la consola Nintendo Switch. Lanzado en marzo de 2020, el juego permite a los jugadores crear y personalizar su propia isla desierta, interactuar con personajes antropomórficos y participar en diversas actividades como la pesca, la jardinería y la decoración.",
    releaseDate: "2020-03-20",
    score: 90,
    image: "https://howlongtobeat.com/games/68240_Animal_Crossing_New_Horizons.jpg",
  },
  {
    slug: "the-witcher-3-wild-hunt",
    title: "The Witcher 3: Wild Hunt",
    description: "Un RPG de acción en un mundo abierto basado en la serie de libros de Andrzej Sapkowski.",
    descriptionTwo: "The Witcher 3: Wild Hunt es un videojuego de rol y acción desarrollado por CD Projekt Red. Lanzado en mayo de 2015, el juego está basado en la serie de libros de fantasía del autor polaco Andrzej Sapkowski. Los jugadores asumen el papel de Geralt de Rivia, un cazador de monstruos conocido como brujo, mientras exploran un vasto mundo abierto lleno de misiones, personajes complejos y decisiones morales que afectan el desarrollo de la historia.",
    releaseDate: "2015-05-19",
    score: 93,
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Witcher_3_cover_art.jpg/250px-Witcher_3_cover_art.jpg",
  }
  
];